<?php

namespace JeffersonGoncalves\KnowledgeBase\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;
use JeffersonGoncalves\KnowledgeBase\Enums\ArticleStatus;
use JeffersonGoncalves\KnowledgeBase\Enums\ArticleVisibility;
use JeffersonGoncalves\KnowledgeBase\Models\Article;

/** @extends Factory<Article> */
class ArticleFactory extends Factory
{
    protected $model = Article::class;

    /** @return array<string, mixed> */
    public function definition(): array
    {
        $title = fake()->sentence();

        return [
            'title' => $title,
            'slug' => Str::slug($title).'-'.Str::random(6),
            'content' => fake()->paragraphs(3, true),
            'excerpt' => fake()->sentence(),
            'status' => ArticleStatus::Draft,
            'visibility' => ArticleVisibility::Public,
        ];
    }

    public function configure(): static
    {
        // uuid is generated by the model's "creating" hook and the counter /
        // version columns are guarded (not mass-assignable), so they are forced
        // here to guarantee sane in-memory defaults before the model is saved.
        return $this->afterMaking(function (Article $article): void {
            $article->forceFill([
                'view_count' => $article->view_count ?? 0,
                'helpful_count' => $article->helpful_count ?? 0,
                'not_helpful_count' => $article->not_helpful_count ?? 0,
                'current_version' => $article->current_version ?? 1,
            ]);
        });
    }

    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ArticleStatus::Published,
            'published_at' => now(),
        ]);
    }

    public function archived(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ArticleStatus::Archived,
        ]);
    }

    public function internal(): static
    {
        return $this->state(fn (array $attributes) => [
            'visibility' => ArticleVisibility::Internal,
        ]);
    }
}
